//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package assets

// Obsidian vault configuration.
const (
	// ObsidianAppConfig is the minimal app.json content that enforces
	// wikilink mode and shows frontmatter properties.
	ObsidianAppConfig = `{
  "useMarkdownLinks": false,
  "showFrontmatter": true,
  "strictLineBreaks": false
}
`
)

// Obsidian vault format templates.
const (
	// ObsidianWikilinkFmt formats a wikilink with display text.
	// Args: target, display.
	ObsidianWikilinkFmt = "[[%s|%s]]"
	// ObsidianWikilinkPlain formats a plain wikilink (no display text).
	// Args: target.
	ObsidianWikilinkPlain = "[[%s]]"
	// ObsidianRelatedHeading is the section heading for the related footer.
	ObsidianRelatedHeading = "## Related Sessions"
	// ObsidianSeeAlso is the label for the see-also section in the footer.
	ObsidianSeeAlso = "**See also**:"
)

// Obsidian vault README template.
const ObsidianReadme = `# journal-obsidian (generated)

This directory is generated by ` + "`ctx journal obsidian`" + ` and is read-only.
Do not edit files here — changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal obsidian
` + "```" + `

## Usage

Open this directory as an Obsidian vault:

1. Open Obsidian
2. Choose "Open folder as vault"
3. Select this directory
`
