version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - gosec
    - unconvert
    - gocritic

  settings:
    govet:
      enable:
        - shadow

  exclusions:
    paths:
      - vendor
      - dist
      - site
    rules:
      # Test files use literal strings for clarity
      - linters: [goconst]
        path: "_test\\.go"
      # Test files construct paths from test constants, not user input
      - linters: [gosec]
        text: "G304"
        path: "_test\\.go"

run:
  timeout: 5m

output:
  formats:
    text:
      colors: true
