//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package cmd

const (
	UseSystemBackup                 = "backup"
	UseSystemBlockDangerousCommands = "block-dangerous-commands"
	UseSystemBlockNonPathCtx        = "block-non-path-ctx"
	UseSystemBootstrap              = "bootstrap"
	UseSystemCheckBackupAge         = "check-backup-age"
	UseSystemCheckCeremonies        = "check-ceremonies"
	UseSystemCheckContextSize       = "check-context-size"
	UseSystemCheckFreshness         = "check-freshness"
	UseSystemCheckJournal           = "check-journal"
	UseSystemCheckKnowledge         = "check-knowledge"
	UseSystemCheckMapStaleness      = "check-map-staleness"
	UseSystemCheckMemoryDrift       = "check-memory-drift"
	UseSystemCheckPersistence       = "check-persistence"
	UseSystemCheckReminders         = "check-reminders"
	UseSystemCheckResources         = "check-resources"
	UseSystemCheckTaskCompletion    = "check-task-completion"
	UseSystemCheckVersion           = "check-version"
	UseSystemContextLoadGate        = "context-load-gate"
	UseSystemEvents                 = "events"
	UseSystemHeartbeat              = "heartbeat"
	UseSystemMarkJournal            = "mark-journal <filename> <stage>"
	UseSystemMarkWrappedUp          = "mark-wrapped-up"
	UseSystemMessage                = "message"
	UseSystemMessageEdit            = "edit <hook> <variant>"
	UseSystemMessageList            = "list"
	UseSystemMessageReset           = "reset <hook> <variant>"
	UseSystemMessageShow            = "show <hook> <variant>"
	UseSystemPause                  = "pause"
	UseSystemPostCommit             = "post-commit"
	UseSystemPrune                  = "prune"
	UseSystemQaReminder             = "qa-reminder"
	UseSystemResources              = "resources"
	UseSystemResume                 = "resume"
	UseSystemSpecsNudge             = "specs-nudge"
	UseSystemStats                  = "stats"
)

const (
	DescKeySystem                       = "system"
	DescKeySystemBackup                 = "system.backup"
	DescKeySystemBlockDangerousCommands = "system.blockdangerouscommands"
	DescKeySystemBlockNonPathCtx        = "system.blocknonpathctx"
	DescKeySystemBootstrap              = "system.bootstrap"
	DescKeySystemCheckBackupAge         = "system.checkbackupage"
	DescKeySystemCheckCeremonies        = "system.checkceremonies"
	DescKeySystemCheckContextSize       = "system.checkcontextsize"
	DescKeySystemCheckFreshness         = "system.checkfreshness"
	DescKeySystemCheckJournal           = "system.checkjournal"
	DescKeySystemCheckKnowledge         = "system.checkknowledge"
	DescKeySystemCheckMapStaleness      = "system.checkmapstaleness"
	DescKeySystemCheckMemoryDrift       = "system.checkmemorydrift"
	DescKeySystemCheckPersistence       = "system.checkpersistence"
	DescKeySystemCheckReminders         = "system.checkreminders"
	DescKeySystemCheckResources         = "system.checkresources"
	DescKeySystemCheckTaskCompletion    = "system.checktaskcompletion"
	DescKeySystemCheckVersion           = "system.checkversion"
	DescKeySystemContextLoadGate        = "system.contextloadgate"
	DescKeySystemEvents                 = "system.events"
	DescKeySystemHeartbeat              = "system.heartbeat"
	DescKeySystemMarkJournal            = "system.markjournal"
	DescKeySystemMarkWrappedUp          = "system.markwrappedup"
	DescKeySystemMessage                = "system.message"
	DescKeySystemMessageEdit            = "system.message.edit"
	DescKeySystemMessageList            = "system.message.list"
	DescKeySystemMessageReset           = "system.message.reset"
	DescKeySystemMessageShow            = "system.message.show"
	DescKeySystemPause                  = "system.pause"
	DescKeySystemPostCommit             = "system.postcommit"
	DescKeySystemPrune                  = "system.prune"
	DescKeySystemQaReminder             = "system.qareminder"
	DescKeySystemResources              = "system.resources"
	DescKeySystemResume                 = "system.resume"
	DescKeySystemSpecsNudge             = "system.specsnudge"
	DescKeySystemStats                  = "system.stats"
)
