//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package tpl

// Agent load and loop script templates.
const (
	// LoadBudget formats the token budget summary line.
	// Args: budget, totalTokens.
	LoadBudget = "Token Budget: %d | Available: %d"

	// LoadTruncated formats the truncation notice for budget-limited output.
	// Args: fileName.
	LoadTruncated = "*[Truncated: %s and remaining" +
		" files excluded due to token budget]*"

	// LoadSectionHeading formats a file section heading in assembled output.
	// Args: title.
	LoadSectionHeading = "## %s"

	// LoopScript is the bash script template for the Ralph Loop.
	// Args: promptFile, completionMsg, maxIterCheck,
	// aiCommand, loopComplete, notifyCmd.
	LoopScript = `#!/bin/bash
#
# Context: Ralph Loop Script
# Generated by: ctx loop
#
# This script runs an AI assistant in a loop until completion.
# The AI works on the same prompt file repeatedly, building on
# previous work visible in files and git history.
#

set -e

PROMPT_FILE="%s"
COMPLETION_SIGNAL="%s"
ITERATION=0

echo "Starting Ralph Loop"
echo "==================="
echo "Prompt: $PROMPT_FILE"
echo "Completion signal: $COMPLETION_SIGNAL"
echo ""

# Ensure prompt file exists
if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: Prompt file not found: $PROMPT_FILE"
    exit 1
fi

while true; do
    ITERATION=$((ITERATION + 1))
    echo ""
    echo "=== Iteration $ITERATION ==="
    echo ""
%s
    # Run the AI tool
    OUTPUT=$(%s 2>&1) || true

    echo "$OUTPUT"

    # Check for completion signal
    if echo "$OUTPUT" | grep -q "$COMPLETION_SIGNAL"; then
        echo ""
        echo "%s"
        echo "Detected completion signal: $COMPLETION_SIGNAL"
        echo "Total iterations: $ITERATION"
        %s
        break
    fi

    # Small delay to prevent runaway loops
    sleep 1
done
`

	// LoopMaxIter is the iteration-limit check block for the loop script.
	// Args: maxIterations, maxIterations, notifyCmd.
	LoopMaxIter = `
    # Check iteration limit
    if [ $ITERATION -ge %d ]; then
        echo "Reached maximum iterations (%d)"
        %s
        break
    fi`

	// LoopNotify is the ctx hook notify call appended to loop completion points.
	LoopNotify = `ctx hook notify --event loop` +
		` "Loop completed after $ITERATION iterations"` +
		` 2>/dev/null || true`

	// LoopCmdClaude is the shell command template for Claude Code.
	// Args: promptFile.
	LoopCmdClaude = `claude --print "$(cat %s)"`

	// LoopCmdAider is the shell command template for Aider.
	// Args: promptFile.
	LoopCmdAider = `aider --message-file %s`

	// LoopCmdGeneric is the shell command placeholder for custom tools.
	// Args: promptFile.
	LoopCmdGeneric = `# Replace with your AI CLI command
    cat %s | your-ai-cli`
)
