//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package tpl

// ObsidianReadme is the README template for the generated Obsidian vault.
// Args: journal source directory path.
//
// This template contains multi-line Markdown with fmt.Sprintf placeholders,
// which cannot be expressed in the YAML short/long text format. It should
// migrate to a Go text/template or an embedded template file when the
// template rendering pipeline is implemented (see TASKS.md).
const ObsidianReadme = `# journal-obsidian (generated)

This directory is generated by ` + "`ctx journal obsidian`" + ` and is read-only.
Do not edit files here - changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal obsidian
` + "```" + `

## Usage

Open this directory as an Obsidian vault:

1. Open Obsidian
2. Choose "Open folder as vault"
3. Select this directory
`
