//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

// Package vscode defines constants for VS Code workspace configuration
// artifacts generated by ctx init.
//
// Provides directory paths, file names, JSON keys, and task configuration
// values used when creating .vscode/ workspace files.
//
// Constant groups:
//   - Dir, file names: workspace directory and configuration file paths
//   - ExtensionID: VS Code Marketplace identifier for the ctx extension
//   - KeyRecommendations: JSON key for extensions.json
//   - KeyVersion, KeyTasks, ...: JSON keys for tasks.json structure
//   - KeyServers, KeyArgs: JSON keys for mcp.json structure
//   - TasksVersion, TypeShell, ...: task configuration values
//
// The Tasks variable holds the label/command pairs for ctx tasks that
// are written into .vscode/tasks.json during initialization.
//
// Constants are referenced by domain packages via config/vscode.*.
package vscode
