//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

// Package vscode defines constants for VS Code workspace configuration
// artifacts generated by ctx init.
package vscode

// Dir is the VS Code workspace configuration directory.
const Dir = ".vscode"

// Configuration file names within .vscode/.
const (
	FileExtensionsJSON = "extensions.json"
	FileTasksJSON      = "tasks.json"
	FileMCPJSON        = "mcp.json"
)

// ExtensionID is the VS Code Marketplace identifier for the ctx extension.
const ExtensionID = "activememory.ctx-context"

// JSON keys for extensions.json.
const (
	KeyRecommendations = "recommendations"
)

// JSON keys for tasks.json.
const (
	KeyCommand = "command"
)

// Task configuration values.
const (
	TasksVersion = "2.0.0"
	TypeShell    = "shell"
	GroupNone    = "none"
	RevealAlways = "always"
	PanelShared  = "shared"
)

// JSON keys for mcp.json.
const (
	KeyServers = "servers"
	KeyArgs    = "args"
)

// Task definitions: label and command pairs for ctx tasks.
var Tasks = []struct {
	Label   string
	Command string
}{
	{"ctx: status", "ctx status"},
	{"ctx: drift", "ctx drift"},
	{"ctx: agent", "ctx agent --budget 4000"},
	{"ctx: journal", "ctx recall export --all && ctx journal site --build"},
	{"ctx: journal-serve", "ctx journal site --serve"},
}
