//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package text

// DescKeys for drift detection.
const (
	DescKeyDriftDeadPath             = "drift.dead-path"
	DescKeyDriftEntryCount           = "drift.entry-count"
	DescKeyDriftMissingFile          = "drift.missing-file"
	DescKeyDriftRegenerated          = "drift.regenerated"
	DescKeyDriftMissingPackage       = "drift.missing-package"
	DescKeyDriftSecret               = "drift.secret"
	DescKeyDriftStaleAge             = "drift.stale-age"
	DescKeyDriftStaleness            = "drift.staleness"
	DescKeyDriftCleared              = "drift.cleared"
	DescKeyDriftApplying             = "drift.applying"
	DescKeyDriftFixedCount           = "drift.fixed-count"
	DescKeyDriftSkippedCount         = "drift.skipped-count"
	DescKeyDriftFixError             = "drift.fix-error"
	DescKeyDriftRechecking           = "drift.rechecking"
	DescKeyDriftFixStaleness         = "drift.fix-staleness"
	DescKeyDriftFixStalenessErr      = "drift.fix-staleness-err"
	DescKeyDriftFixMissing           = "drift.fix-missing"
	DescKeyDriftFixMissingErr        = "drift.fix-missing-err"
	DescKeyDriftSkipDeadPath         = "drift.skip-dead-path"
	DescKeyDriftSkipStaleAge         = "drift.skip-stale-age"
	DescKeyDriftSkipSensitiveFile    = "drift.skip-sensitive-file"
	DescKeyDriftArchived             = "drift.archived"
	DescKeyDriftReportHeading        = "drift.report-heading"
	DescKeyDriftReportSeparator      = "drift.report-separator"
	DescKeyDriftViolationsHeading    = "drift.violations-heading"
	DescKeyDriftViolationLine        = "drift.violation-line"
	DescKeyDriftViolationLineLoc     = "drift.violation-line-loc"
	DescKeyDriftViolationRule        = "drift.violation-rule"
	DescKeyDriftWarningsHeading      = "drift.warnings-heading"
	DescKeyDriftPathRefsLabel        = "drift.path-refs-label"
	DescKeyDriftPathRefLine          = "drift.path-ref-line"
	DescKeyDriftStalenessLabel       = "drift.staleness-label"
	DescKeyDriftStalenessLine        = "drift.staleness-line"
	DescKeyDriftOtherLabel           = "drift.other-label"
	DescKeyDriftOtherLine            = "drift.other-line"
	DescKeyDriftPassedHeading        = "drift.passed-heading"
	DescKeyDriftPassedLine           = "drift.passed-line"
	DescKeyDriftStatusViolation      = "drift.status-violation"
	DescKeyDriftStatusWarning        = "drift.status-warning"
	DescKeyDriftStatusOK             = "drift.status-ok"
	DescKeyDriftCheckPathRefs        = "drift.check-path-refs"
	DescKeyDriftCheckStaleness       = "drift.check-staleness"
	DescKeyDriftCheckConstitution    = "drift.check-constitution"
	DescKeyDriftCheckRequired        = "drift.check-required"
	DescKeyDriftCheckFileAge         = "drift.check-file-age"
	DescKeyDriftStaleHeader          = "drift.stale-header"
	DescKeyDriftCheckTemplateHeader  = "drift.check-template-header"
	DescKeyDriftInvalidTool          = "drift.invalid-tool"
	DescKeyDriftHookNoExec           = "drift.hook-no-exec"
	DescKeyDriftStaleSyncFile        = "drift.stale-sync-file"
	DescKeyDriftToolSuffix           = "drift.tool-suffix"
	DescKeyVersionDriftRelayMessage  = "version-drift.relay-message"
	DescKeyWriteVersionDriftFallback = "write.version-drift-fallback"
)
