//   /    ctx:                         https://ctx.ist
// ,'`./    do you remember?
// `.,'\\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package text

const (
	TextDescKeyAgentInstruction = "agent.instruction"

	TextDescKeyErrContextDirNotFound = "err.context.dir-not-found"

	TextDescKeyErrConfigGoldenNotFound     = "err.config.golden-not-found"
	TextDescKeyErrConfigInvalidTool        = "err.config.invalid-tool"
	TextDescKeyErrConfigMarshalPlugins     = "err.config.marshal-plugins"
	TextDescKeyErrConfigMarshalSettings    = "err.config.marshal-settings"
	TextDescKeyErrConfigReadEmbeddedSchema = "err.config.read-embedded-schema"
	TextDescKeyErrConfigReadProfile        = "err.config.read-profile"
	TextDescKeyErrConfigSettingsNotFound   = "err.config.settings-not-found"
	TextDescKeyErrConfigUnknownFormat      = "err.config.unknown-format"
	TextDescKeyErrConfigUnknownProfile     = "err.config.unknown-profile"
	TextDescKeyErrConfigUnknownProjectType = "err.config.unknown-project-type"
	TextDescKeyErrConfigUnknownUpdateType  = "err.config.unknown-update-type"
	TextDescKeyErrConfigUnsupportedTool    = "err.config.unsupported-tool"

	TextDescKeyErrCryptoCiphertextTooShort = "err.crypto.ciphertext-too-short"
	TextDescKeyErrCryptoCreateCipher       = "err.crypto.create-cipher"
	TextDescKeyErrCryptoCreateGCM          = "err.crypto.create-gcm"
	TextDescKeyErrCryptoDecrypt            = "err.crypto.decrypt"
	TextDescKeyErrCryptoDecryptFailed      = "err.crypto.decrypt-failed"
	TextDescKeyErrCryptoEncryptFailed      = "err.crypto.encrypt-failed"
	TextDescKeyErrCryptoGenerateKey        = "err.crypto.generate-key"
	TextDescKeyErrCryptoGenerateNonce      = "err.crypto.generate-nonce"
	TextDescKeyErrCryptoInvalidKeySize     = "err.crypto.invalid-key-size"
	TextDescKeyErrCryptoLoadKey            = "err.crypto.load-key"
	TextDescKeyErrCryptoMkdirKeyDir        = "err.crypto.mkdir-key-dir"
	TextDescKeyErrCryptoNoKeyAt            = "err.crypto.no-key-at"
	TextDescKeyErrCryptoReadKey            = "err.crypto.read-key"
	TextDescKeyErrCryptoSaveKey            = "err.crypto.save-key"
	TextDescKeyErrCryptoWriteKey           = "err.crypto.write-key"

	TextDescKeyErrDateInvalidDate         = "err.date.invalid-date"
	TextDescKeyErrDateInvalidDateValue    = "err.date.invalid-date-value"
	TextDescKeyErrDepsCargoMetadataFailed = "err.deps.cargo-metadata-failed"

	TextDescKeyErrDepsCargoNotFound      = "err.deps.cargo-not-found"
	TextDescKeyErrDepsParseCargoMetadata = "err.deps.parse-cargo-metadata"

	TextDescKeyErrFsBoundaryViolation    = "err.fs.boundary-violation"
	TextDescKeyErrFsCreateDir            = "err.fs.create-dir"
	TextDescKeyErrFsDirNotFound          = "err.fs.dir-not-found"
	TextDescKeyErrFsFileAmend            = "err.fs.file-amend"
	TextDescKeyErrFsFileRead             = "err.fs.file-read"
	TextDescKeyErrFsFileUpdate           = "err.fs.file-update"
	TextDescKeyErrFsFileWrite            = "err.fs.file-write"
	TextDescKeyErrFsMkdir                = "err.fs.mkdir"
	TextDescKeyErrFsNoInput              = "err.fs.no-input"
	TextDescKeyErrFsNotDirectory         = "err.fs.not-directory"
	TextDescKeyErrFsOpenFile             = "err.fs.open-file"
	TextDescKeyErrFsPathEscapesBase      = "err.fs.path-escapes-base"
	TextDescKeyErrFsReadDir              = "err.fs.read-dir"
	TextDescKeyErrFsReadDirectory        = "err.fs.read-directory"
	TextDescKeyErrFsReadFile             = "err.fs.read-file"
	TextDescKeyErrFsReadInput            = "err.fs.read-input"
	TextDescKeyErrFsReadInputStream      = "err.fs.read-input-stream"
	TextDescKeyErrFsRefuseSystemPath     = "err.fs.refuse-system-path"
	TextDescKeyErrFsRefuseSystemPathRoot = "err.fs.refuse-system-path-root"
	TextDescKeyErrFsResolveBase          = "err.fs.resolve-base"
	TextDescKeyErrFsResolvePath          = "err.fs.resolve-path"
	TextDescKeyErrFsStatPath             = "err.fs.stat-path"
	TextDescKeyErrFsWriteFileFailed      = "err.fs.write-file-failed"
	TextDescKeyErrFsWriteMerged          = "err.fs.write-merged"

	TextDescKeyErrGitNotInGitRepo = "err.git.not-in-git-repo"

	TextDescKeyErrHookEmbeddedTemplateNotFound = "err.hook.embedded-template-not-found"
	TextDescKeyErrHookOverrideExists           = "err.hook.override-exists"
	TextDescKeyErrHookRemoveOverride           = "err.hook.remove-override"
	TextDescKeyErrHookUnknownHook              = "err.hook.unknown-hook"
	TextDescKeyErrHookUnknownVariant           = "err.hook.unknown-variant"
	TextDescKeyErrHookWriteOverride            = "err.hook.write-override"

	TextDescKeyErrHttpParseURL         = "err.http.parse-url"
	TextDescKeyErrHttpTooManyRedirects = "err.http.too-many-redirects"
	TextDescKeyErrHttpUnsafeURLScheme  = "err.http.unsafe-url-scheme"

	TextDescKeyErrInitCtxNotInPath          = "err.init.ctx-not-in-path"
	TextDescKeyErrInitContextNotInitialized = "err.init.context-not-initialized"
	TextDescKeyErrInitCreateMakefile        = "err.init.create-makefile"
	TextDescKeyErrInitDetectReferenceTime   = "err.init.detect-reference-time"
	TextDescKeyErrInitHomeDir               = "err.init.home-dir"
	TextDescKeyErrInitNotInitialized        = "err.init.not-initialized"
	TextDescKeyErrInitReadInitTemplate      = "err.init.read-init-template"
	TextDescKeyErrInitReadProjectReadme     = "err.init.read-project-readme"

	TextDescKeyErrJournalLoadJournalState      = "err.journal.load-journal-state"
	TextDescKeyErrJournalNoEntriesMatch        = "err.journal.no-entries-match"
	TextDescKeyErrJournalNoJournalDir          = "err.journal.no-journal-dir"
	TextDescKeyErrJournalNoJournalEntries      = "err.journal.no-journal-entries"
	TextDescKeyErrJournalReadJournalDir        = "err.journal.read-journal-dir"
	TextDescKeyErrJournalRegenerateRequiresAll = "err.journal.regenerate-requires-all"
	TextDescKeyErrJournalSaveJournalState      = "err.journal.save-journal-state"
	TextDescKeyErrJournalScanJournal           = "err.journal.scan-journal"
	TextDescKeyErrJournalStageNotSet           = "err.journal.stage-not-set"
	TextDescKeyErrJournalUnknownStage          = "err.journal.unknown-stage"

	TextDescKeyErrMemoryDiscoverNoMemory    = "err.memory.discover-no-memory"
	TextDescKeyErrMemoryDiscoverResolveHome = "err.memory.discover-resolve-home"
	TextDescKeyErrMemoryDiscoverResolveRoot = "err.memory.discover-resolve-root"
	TextDescKeyErrMemoryArchivePrevious     = "err.memory.memory-archive-previous"
	TextDescKeyErrMemoryCreateArchiveDir    = "err.memory.memory-create-archive-dir"
	TextDescKeyErrMemoryCreateDir           = "err.memory.memory-create-dir"
	TextDescKeyErrMemoryDiffFailed          = "err.memory.memory-diff-failed"
	TextDescKeyErrMemoryDiscoverFailed      = "err.memory.memory-discover-failed"
	TextDescKeyErrMemoryNotFound            = "err.memory.memory-not-found"
	TextDescKeyErrMemoryReadDiffSource      = "err.memory.memory-read-diff-source"
	TextDescKeyErrMemoryReadMirror          = "err.memory.memory-read-mirror"
	TextDescKeyErrMemoryReadMirrorArchive   = "err.memory.memory-read-mirror-archive"
	TextDescKeyErrMemoryReadSource          = "err.memory.memory-read-source"
	TextDescKeyErrMemorySelectContent       = "err.memory.memory-select-content"
	TextDescKeyErrMemoryWriteArchive        = "err.memory.memory-write-archive"
	TextDescKeyErrMemoryWriteMemory         = "err.memory.memory-write-memory"
	TextDescKeyErrMemoryWriteMirror         = "err.memory.memory-write-mirror"
	TextDescKeyErrMemoryPublishFailed       = "err.memory.publish-failed"
	TextDescKeyErrMemoryReadMemory          = "err.memory.read-memory"
	TextDescKeyErrMemorySelectContentFailed = "err.memory.select-content-failed"
	TextDescKeyErrMemorySyncFailed          = "err.memory.sync-failed"
	TextDescKeyErrMemoryWriteMemoryTop      = "err.memory.write-memory"

	TextDescKeyErrNotifyLoadWebhook      = "err.notify.load-webhook"
	TextDescKeyErrNotifyMarshalPayload   = "err.notify.marshal-payload"
	TextDescKeyErrNotifySaveWebhook      = "err.notify.save-webhook"
	TextDescKeyErrNotifySendNotification = "err.notify.send-notification"
	TextDescKeyErrNotifyWebhookEmpty     = "err.notify.webhook-empty"

	TextDescKeyErrPadBlobAppendNotAllowed  = "err.pad.blob-append-not-allowed"
	TextDescKeyErrPadBlobPrependNotAllowed = "err.pad.blob-prepend-not-allowed"
	TextDescKeyErrPadEditBlobTextConflict  = "err.pad.edit-blob-text-conflict"
	TextDescKeyErrPadEditNoMode            = "err.pad.edit-no-mode"
	TextDescKeyErrPadEditTextConflict      = "err.pad.edit-text-conflict"
	TextDescKeyErrPadEntryRange            = "err.pad.entry-range"
	TextDescKeyErrPadFileTooLarge          = "err.pad.file-too-large"
	TextDescKeyErrPadInvalidIndex          = "err.pad.invalid-index"
	TextDescKeyErrPadNoConflictFiles       = "err.pad.no-conflict-files"
	TextDescKeyErrPadNotBlobEntry          = "err.pad.not-blob-entry"
	TextDescKeyErrPadOutFlagRequiresBlob   = "err.pad.out-flag-requires-blob"
	TextDescKeyErrPadReadScratchpad        = "err.pad.read-scratchpad"
	TextDescKeyErrPadResolveNotEncrypted   = "err.pad.resolve-not-encrypted"

	TextDescKeyErrParserFileError = "err.parser.file-error"
	TextDescKeyErrParserNoMatch   = "err.parser.no-match"
	TextDescKeyErrParserOpenFile  = "err.parser.open-file"
	TextDescKeyErrParserReadFile  = "err.parser.read-file"
	TextDescKeyErrParserScanFile  = "err.parser.scan-file"
	TextDescKeyErrParserUnmarshal = "err.parser.unmarshal"
	TextDescKeyErrParserWalkDir   = "err.parser.walk-dir"

	TextDescKeyErrPromptExists                 = "err.prompt.exists"
	TextDescKeyErrPromptListEntryTemplates     = "err.prompt.list-entry-templates"
	TextDescKeyErrPromptListPromptTemplates    = "err.prompt.list-prompt-templates"
	TextDescKeyErrPromptListTemplates          = "err.prompt.list-templates"
	TextDescKeyErrPromptMarkerNotFound         = "err.prompt.marker-not-found"
	TextDescKeyErrPromptNoPromptTemplate       = "err.prompt.no-prompt-template"
	TextDescKeyErrPromptNoTemplate             = "err.prompt.no-template"
	TextDescKeyErrPromptNotFound               = "err.prompt.not-found"
	TextDescKeyErrPromptReadEntryTemplate      = "err.prompt.read-entry-template"
	TextDescKeyErrPromptReadPromptTemplate     = "err.prompt.read-prompt-template"
	TextDescKeyErrPromptReadTemplate           = "err.prompt.read-template"
	TextDescKeyErrPromptRemovePrompt           = "err.prompt.remove-prompt"
	TextDescKeyErrPromptTemplateMissingMarkers = "err.prompt.template-missing-markers"

	TextDescKeyErrRecallEventLogRead        = "err.recall.event-log-read"
	TextDescKeyErrRecallOpenLogFile         = "err.recall.open-log-file"
	TextDescKeyErrRecallReindexFileNotFound = "err.recall.reindex-file-not-found"
	TextDescKeyErrRecallReindexFileRead     = "err.recall.reindex-file-read"
	TextDescKeyErrRecallReindexFileWrite    = "err.recall.reindex-file-write"
	TextDescKeyErrRecallStatsGlob           = "err.recall.stats-glob"

	TextDescKeyErrReminderInvalidID      = "err.reminder.invalid-id"
	TextDescKeyErrReminderParseReminders = "err.reminder.parse-reminders"
	TextDescKeyErrReminderReadReminders  = "err.reminder.read-reminders"
	TextDescKeyErrReminderIDRequired     = "err.reminder.reminder-id-required"
	TextDescKeyErrReminderNotFound       = "err.reminder.reminder-not-found"

	TextDescKeyErrSessionAllWithPattern      = "err.session.all-with-pattern"
	TextDescKeyErrSessionAllWithSessionID    = "err.session.all-with-session-id"
	TextDescKeyErrSessionAmbiguousQuery      = "err.session.ambiguous-query"
	TextDescKeyErrSessionFindSessions        = "err.session.find-sessions"
	TextDescKeyErrSessionNoSessionsFound     = "err.session.no-sessions-found"
	TextDescKeyErrSessionNoSessionsFoundHint = "err.session.no-sessions-found-hint"
	TextDescKeyErrSessionIDRequired          = "err.session.session-id-required"
	TextDescKeyErrSessionNotFound            = "err.session.session-not-found"
	TextDescKeyErrSiteMarshalFeed            = "err.site.marshal-feed"
	TextDescKeyErrSiteNoSiteConfig           = "err.site.no-site-config"

	TextDescKeyErrSiteZensicalNotFound = "err.site.zensical-not-found"

	TextDescKeyErrSkillList = "err.skill.skill-list"
	TextDescKeyErrSkillRead = "err.skill.skill-read"

	TextDescKeyErrStateLoadState       = "err.state.load-state"
	TextDescKeyErrStateReadingStateDir = "err.state.reading-state-dir"
	TextDescKeyErrStateSaveState       = "err.state.save-state"

	TextDescKeyErrTaskNoCompletedTasks = "err.task.no-completed-tasks"
	TextDescKeyErrTaskNoTaskMatch      = "err.task.no-task-match"
	TextDescKeyErrTaskNoTaskSpecified  = "err.task.no-task-specified"
	TextDescKeyErrTaskSnapshotWrite    = "err.task.snapshot-write"
	TextDescKeyErrTaskFileNotFound     = "err.task.task-file-not-found"
	TextDescKeyErrTaskFileRead         = "err.task.task-file-read"
	TextDescKeyErrTaskFileWrite        = "err.task.task-file-write"
	TextDescKeyErrTaskMultipleMatches  = "err.task.task-multiple-matches"
	TextDescKeyErrTaskNotFound         = "err.task.task-not-found"

	TextDescKeyErrValidateContextDirSymlink  = "err.validate.context-dir-symlink"
	TextDescKeyErrValidateContextFileSymlink = "err.validate.context-file-symlink"
	TextDescKeyErrValidateContextOutsideRoot = "err.validate.context-outside-root"
	TextDescKeyErrValidateInvalidSelection   = "err.validate.invalid-selection"
	TextDescKeyErrValidateUnknownDocument    = "err.validate.unknown-document"
	TextDescKeyErrValidateArgRequired        = "err.validation.arg-required"
	TextDescKeyErrValidateCtxNotInPath       = "err.validation.ctx-not-in-path"
	TextDescKeyErrValidateDriftViolations    = "err.validation.drift-violations"
	TextDescKeyErrValidateFlagRequired       = "err.validation.flag-required"
	TextDescKeyErrValidateParseFile          = "err.validation.parse-file"
	TextDescKeyErrValidateWorkingDirectory   = "err.validation.working-directory"

	TextDescKeyEventsEmpty       = "events.empty"
	TextDescKeyEventsHumanFormat = "events.human-format"
	TextDescKeyEventsCloseError  = "events.close-error"
	TextDescKeyEventsWriteError  = "events.write-error"

	TextDescKeyStatsEmpty        = "stats.empty"
	TextDescKeyStatsHeaderFormat = "stats.header-format"
	TextDescKeyStatsLineFormat   = "stats.line-format"

	TextDescKeyCheckContextSizeBillingBoxTitle       = "check-context-size.billing-box-title"
	TextDescKeyCheckContextSizeBillingFallback       = "check-context-size.billing-fallback"
	TextDescKeyCheckContextSizeBillingRelayFormat    = "check-context-size.billing-relay-format"
	TextDescKeyCheckContextSizeBillingRelayPrefix    = "check-context-size.billing-relay-prefix"
	TextDescKeyCheckContextSizeCheckpointBoxTitle    = "check-context-size.checkpoint-box-title"
	TextDescKeyCheckContextSizeCheckpointFallback    = "check-context-size.checkpoint-fallback"
	TextDescKeyCheckContextSizeCheckpointRelayFormat = "check-context-size.checkpoint-relay-format"
	TextDescKeyCheckContextSizeOversizeFallback      = "check-context-size.oversize-fallback"
	TextDescKeyCheckContextSizeRelayPrefix           = "check-context-size.relay-prefix"
	TextDescKeyCheckContextSizeRunningLowSuffix      = "check-context-size.running-low-suffix"
	TextDescKeyCheckContextSizeSilentLogFormat       = "check-context-size.silent-log-format"
	TextDescKeyCheckContextSizeSilencedCheckpointLog = "check-context-size.silenced-checkpoint-log"
	TextDescKeyCheckContextSizeCheckpointLogFormat   = "check-context-size.checkpoint-log-format"
	TextDescKeyCheckContextSizeSuppressedLogFormat   = "check-context-size.suppressed-log-format"
	TextDescKeyCheckContextSizeSilencedWindowLog     = "check-context-size.silenced-window-log"
	TextDescKeyCheckContextSizeWindowLogFormat       = "check-context-size.window-log-format"
	TextDescKeyCheckContextSizeSilencedBillingLog    = "check-context-size.silenced-billing-log"
	TextDescKeyCheckContextSizeBillingLogFormat      = "check-context-size.billing-log-format"
	TextDescKeyCheckContextSizeTokenLow              = "check-context-size.token-low"
	TextDescKeyCheckContextSizeTokenNormal           = "check-context-size.token-normal"
	TextDescKeyCheckContextSizeTokenUsage            = "check-context-size.token-usage"
	TextDescKeyCheckContextSizeWindowBoxTitle        = "check-context-size.window-box-title"
	TextDescKeyCheckContextSizeWindowFallback        = "check-context-size.window-fallback"
	TextDescKeyCheckContextSizeWindowRelayFormat     = "check-context-size.window-relay-format"

	TextDescKeyCheckJournalBoxTitle           = "check-journal.box-title"
	TextDescKeyCheckJournalFallbackBoth       = "check-journal.fallback-both"
	TextDescKeyCheckJournalFallbackUnenriched = "check-journal.fallback-unenriched"
	TextDescKeyCheckJournalFallbackUnexported = "check-journal.fallback-unexported"
	TextDescKeyCheckJournalRelayFormat        = "check-journal.relay-format"
	TextDescKeyCheckJournalRelayPrefix        = "check-journal.relay-prefix"

	TextDescKeyCheckKnowledgeBoxTitle      = "check-knowledge.box-title"
	TextDescKeyCheckKnowledgeFallback      = "check-knowledge.fallback"
	TextDescKeyCheckKnowledgeFindingFormat = "check-knowledge.finding-format"
	TextDescKeyCheckKnowledgeRelayMessage  = "check-knowledge.relay-message"
	TextDescKeyCheckKnowledgeRelayPrefix   = "check-knowledge.relay-prefix"

	TextDescKeyCheckPersistenceBoxTitle          = "check-persistence.box-title"
	TextDescKeyCheckPersistenceBoxTitleFormat    = "check-persistence.box-title-format"
	TextDescKeyCheckPersistenceCheckpointFormat  = "check-persistence.checkpoint-format"
	TextDescKeyCheckPersistenceFallback          = "check-persistence.fallback"
	TextDescKeyCheckPersistenceInitLogFormat     = "check-persistence.init-log-format"
	TextDescKeyCheckPersistenceModifiedLogFormat = "check-persistence.modified-log-format"
	TextDescKeyCheckPersistenceRelayFormat       = "check-persistence.relay-format"
	TextDescKeyCheckPersistenceRelayPrefix       = "check-persistence.relay-prefix"
	TextDescKeyCheckPersistenceSilencedLogFormat = "check-persistence.silenced-log-format"
	TextDescKeyCheckPersistenceSilentLogFormat   = "check-persistence.silent-log-format"
	TextDescKeyCheckPersistenceStateFormat       = "check-persistence.state-format"

	TextDescKeyCheckVersionBoxTitle            = "check-version.box-title"
	TextDescKeyCheckVersionFallback            = "check-version.fallback"
	TextDescKeyCheckVersionKeyBoxTitle         = "check-version.key-box-title"
	TextDescKeyCheckVersionKeyFallback         = "check-version.key-fallback"
	TextDescKeyCheckVersionKeyRelayFormat      = "check-version.key-relay-format"
	TextDescKeyCheckVersionKeyRelayPrefix      = "check-version.key-relay-prefix"
	TextDescKeyCheckVersionMismatchRelayFormat = "check-version.mismatch-relay-format"
	TextDescKeyCheckVersionRelayPrefix         = "check-version.relay-prefix"

	TextDescKeyCheckMapStalenessBoxTitle     = "check-map-staleness.box-title"
	TextDescKeyCheckMapStalenessFallback     = "check-map-staleness.fallback"
	TextDescKeyCheckMapStalenessRelayMessage = "check-map-staleness.relay-message"
	TextDescKeyCheckMapStalenessRelayPrefix  = "check-map-staleness.relay-prefix"

	TextDescKeyCheckMemoryDriftBoxTitle     = "check-memory-drift.box-title"
	TextDescKeyCheckMemoryDriftContent      = "check-memory-drift.content"
	TextDescKeyCheckMemoryDriftRelayMessage = "check-memory-drift.relay-message"
	TextDescKeyCheckMemoryDriftRelayPrefix  = "check-memory-drift.relay-prefix"

	TextDescKeyCeremonyBoxBoth          = "ceremony.box-both"
	TextDescKeyCeremonyBoxRemember      = "ceremony.box-remember"
	TextDescKeyCeremonyBoxWrapup        = "ceremony.box-wrapup"
	TextDescKeyCeremonyFallbackBoth     = "ceremony.fallback-both"
	TextDescKeyCeremonyFallbackRemember = "ceremony.fallback-remember"
	TextDescKeyCeremonyFallbackWrapup   = "ceremony.fallback-wrapup"
	TextDescKeyCeremonyRelayMessage     = "ceremony.relay-message"
	TextDescKeyCeremonyRelayPrefix      = "ceremony.relay-prefix"

	TextDescKeyCheckRemindersBoxTitle       = "check-reminders.box-title"
	TextDescKeyCheckRemindersDismissHint    = "check-reminders.dismiss-hint"
	TextDescKeyCheckRemindersDismissAllHint = "check-reminders.dismiss-all-hint"
	TextDescKeyCheckRemindersItemFormat     = "check-reminders.item-format"
	TextDescKeyCheckRemindersNudgeFormat    = "check-reminders.nudge-format"
	TextDescKeyCheckRemindersRelayPrefix    = "check-reminders.relay-prefix"

	TextDescKeyCheckResourcesBoxTitle        = "check-resources.box-title"
	TextDescKeyCheckResourcesFallbackLow     = "check-resources.fallback-low"
	TextDescKeyCheckResourcesFallbackPersist = "check-resources.fallback-persist"
	TextDescKeyCheckResourcesFallbackEnd     = "check-resources.fallback-end"
	TextDescKeyCheckResourcesRelayMessage    = "check-resources.relay-message"
	TextDescKeyCheckResourcesRelayPrefix     = "check-resources.relay-prefix"

	TextDescKeyCheckTaskCompletionFallback     = "check-task-completion.fallback"
	TextDescKeyCheckTaskCompletionNudgeMessage = "check-task-completion.nudge-message"

	TextDescKeyRelayPrefixFormat        = "relay.prefix-format"
	TextDescKeyVersionDriftRelayMessage = "version-drift.relay-message"

	TextDescKeyChangesFallbackLabel = "changes.fallback-label"
	TextDescKeyChangesSincePrefix   = "changes.since-prefix"

	TextDescKeyDoctorContextFileFormat           = "doctor.context-file.format"
	TextDescKeyDoctorContextInitializedError     = "doctor.context-initialized.error"
	TextDescKeyDoctorContextInitializedOk        = "doctor.context-initialized.ok"
	TextDescKeyDoctorContextSizeFormat           = "doctor.context-size.format"
	TextDescKeyDoctorContextSizeWarningSuffix    = "doctor.context-size.warning-suffix"
	TextDescKeyDoctorCtxrcValidationError        = "doctor.ctxrc-validation.error"
	TextDescKeyDoctorCtxrcValidationOk           = "doctor.ctxrc-validation.ok"
	TextDescKeyDoctorCtxrcValidationOkNoFile     = "doctor.ctxrc-validation.ok-no-file"
	TextDescKeyDoctorCtxrcValidationWarning      = "doctor.ctxrc-validation.warning"
	TextDescKeyDoctorDriftDetected               = "doctor.drift.detected"
	TextDescKeyDoctorDriftOk                     = "doctor.drift.ok"
	TextDescKeyDoctorDriftViolations             = "doctor.drift.violations"
	TextDescKeyDoctorDriftWarningLoad            = "doctor.drift.warning-load"
	TextDescKeyDoctorDriftWarnings               = "doctor.drift.warnings"
	TextDescKeyDoctorEventLoggingInfo            = "doctor.event-logging.info"
	TextDescKeyDoctorEventLoggingOk              = "doctor.event-logging.ok"
	TextDescKeyDoctorOutputHeader                = "doctor.output.header"
	TextDescKeyDoctorOutputResultLine            = "doctor.output.result-line"
	TextDescKeyDoctorOutputSeparator             = "doctor.output.separator"
	TextDescKeyDoctorOutputSummary               = "doctor.output.summary"
	TextDescKeyDoctorPluginEnabledGlobalOk       = "doctor.plugin-enabled-global.ok"
	TextDescKeyDoctorPluginEnabledLocalOk        = "doctor.plugin-enabled-local.ok"
	TextDescKeyDoctorPluginEnabledWarning        = "doctor.plugin-enabled.warning"
	TextDescKeyDoctorPluginInstalledInfo         = "doctor.plugin-installed.info"
	TextDescKeyDoctorPluginInstalledOk           = "doctor.plugin-installed.ok"
	TextDescKeyDoctorRecentEventsInfo            = "doctor.recent-events.info"
	TextDescKeyDoctorRecentEventsOk              = "doctor.recent-events.ok"
	TextDescKeyDoctorRemindersInfo               = "doctor.reminders.info"
	TextDescKeyDoctorRemindersOk                 = "doctor.reminders.ok"
	TextDescKeyDoctorRequiredFilesError          = "doctor.required-files.error"
	TextDescKeyDoctorRequiredFilesOk             = "doctor.required-files.ok"
	TextDescKeyDoctorResourceDiskFormat          = "doctor.resource-disk.format"
	TextDescKeyDoctorResourceLoadFormat          = "doctor.resource-load.format"
	TextDescKeyDoctorResourceMemoryFormat        = "doctor.resource-memory.format"
	TextDescKeyDoctorResourceSwapFormat          = "doctor.resource-swap.format"
	TextDescKeyDoctorTaskCompletionFormat        = "doctor.task-completion.format"
	TextDescKeyDoctorTaskCompletionWarningSuffix = "doctor.task-completion.warning-suffix"
	TextDescKeyDoctorWebhookInfo                 = "doctor.webhook.info"
	TextDescKeyDoctorWebhookOk                   = "doctor.webhook.ok"

	TextDescKeyImportCountConvention = "import.count-convention"
	TextDescKeyImportCountDecision   = "import.count-decision"
	TextDescKeyImportCountLearning   = "import.count-learning"
	TextDescKeyImportCountTask       = "import.count-task"

	TextDescKeyHookAider          = "hook.aider"
	TextDescKeyHookClaude         = "hook.claude"
	TextDescKeyHookCopilot        = "hook.copilot"
	TextDescKeyHookCursor         = "hook.cursor"
	TextDescKeyHookSupportedTools = "hook.supported-tools"
	TextDescKeyHookWindsurf       = "hook.windsurf"

	TextDescKeyTimeAgo     = "time.ago"
	TextDescKeyTimeDay     = "time.day"
	TextDescKeyTimeHour    = "time.hour"
	TextDescKeyTimeJustNow = "time.just-now"
	TextDescKeyTimeMinute  = "time.minute"

	TextDescKeyConfirmProceed = "confirm.proceed"

	TextDescKeySyncDepsDescription   = "sync.deps.description"
	TextDescKeySyncDepsSuggestion    = "sync.deps.suggestion"
	TextDescKeySyncConfigDescription = "sync.config.description"
	TextDescKeySyncConfigSuggestion  = "sync.config.suggestion"
	TextDescKeySyncDirDescription    = "sync.dir.description"
	TextDescKeySyncDirSuggestion     = "sync.dir.suggestion"

	TextDescKeyBlockNonPathRelayMessage = "block.non-path-relay-message"
	TextDescKeyBlockConstitutionSuffix  = "block.constitution-suffix"
	TextDescKeyBlockMidSudo             = "block.mid-sudo"
	TextDescKeyBlockMidGitPush          = "block.mid-git-push"
	TextDescKeyBlockCpToBin             = "block.cp-to-bin"
	TextDescKeyBlockInstallToLocalBin   = "block.install-to-local-bin"
	TextDescKeyBlockDotSlash            = "block.dot-slash"
	TextDescKeyBlockGoRun               = "block.go-run"
	TextDescKeyBlockAbsolutePath        = "block.absolute-path"

	TextDescKeyPadKeyCreated = "pad.key-created"

	TextDescKeyParserGitNotFound = "parser.git-not-found"

	TextDescKeyPauseConfirmed = "pause.confirmed"

	TextDescKeyPostCommitFallback     = "post-commit.fallback"
	TextDescKeyPostCommitRelayMessage = "post-commit.relay-message"

	TextDescKeyPruneDryRunLine    = "prune.dry-run-line"
	TextDescKeyPruneDryRunSummary = "prune.dry-run-summary"
	TextDescKeyPruneErrorLine     = "prune.error-line"
	TextDescKeyPruneSummary       = "prune.summary"

	TextDescKeyMarkJournalChecked = "mark-journal.checked"
	TextDescKeyMarkJournalMarked  = "mark-journal.marked"

	TextDescKeyMarkWrappedUpConfirmed = "mark-wrapped-up.confirmed"

	TextDescKeyMessageCtxSpecificWarning = "message.ctx-specific-warning"

	TextDescKeyMessageEditHint = "message.edit-hint"

	TextDescKeyMessageListHeaderCategory = "message.list-header-category"
	TextDescKeyMessageListHeaderHook     = "message.list-header-hook"
	TextDescKeyMessageListHeaderOverride = "message.list-header-override"
	TextDescKeyMessageListHeaderVariant  = "message.list-header-variant"

	TextDescKeyMessageNoOverride      = "message.no-override"
	TextDescKeyMessageOverrideCreated = "message.override-created"
	TextDescKeyMessageOverrideLabel   = "message.override-label"
	TextDescKeyMessageOverrideRemoved = "message.override-removed"

	TextDescKeyMessageSourceDefault  = "message.source-default"
	TextDescKeyMessageSourceOverride = "message.source-override"

	TextDescKeyMessageTemplateVarsLabel = "message.template-vars-label"
	TextDescKeyMessageTemplateVarsNone  = "message.template-vars-none"

	TextDescKeySpecsNudgeFallback     = "specs-nudge.fallback"
	TextDescKeySpecsNudgeNudgeMessage = "specs-nudge.nudge-message"

	TextDescKeyQaReminderFallback     = "qa-reminder.fallback"
	TextDescKeyQaReminderRelayMessage = "qa-reminder.relay-message"

	TextDescKeyResourcesAlertDisk    = "resources.alert-disk"
	TextDescKeyResourcesAlertLoad    = "resources.alert-load"
	TextDescKeyResourcesAlertMemory  = "resources.alert-memory"
	TextDescKeyResourcesAlertSwap    = "resources.alert-swap"
	TextDescKeyResourcesAlertDanger  = "resources.alert-danger"
	TextDescKeyResourcesAlertWarning = "resources.alert-warning"
	TextDescKeyResourcesAlerts       = "resources.alerts"
	TextDescKeyResourcesAllClear     = "resources.all-clear"
	TextDescKeyResourcesHeader       = "resources.header"
	TextDescKeyResourcesSeparator    = "resources.separator"
	TextDescKeyResourcesStatusDanger = "resources.status-danger"
	TextDescKeyResourcesStatusOk     = "resources.status-ok"
	TextDescKeyResourcesStatusWarn   = "resources.status-warn"
	TextDescKeyResumeConfirmed       = "resume.confirmed"

	TextDescKeyRcParseWarning = "rc.parse_warning"

	TextDescKeySummaryActive     = "summary.active"
	TextDescKeySummaryCompleted  = "summary.completed"
	TextDescKeySummaryDecision   = "summary.decision"
	TextDescKeySummaryDecisions  = "summary.decisions"
	TextDescKeySummaryEmpty      = "summary.empty"
	TextDescKeySummaryInvariants = "summary.invariants"
	TextDescKeySummaryLoaded     = "summary.loaded"
	TextDescKeySummaryTerm       = "summary.term"
	TextDescKeySummaryTerms      = "summary.terms"

	TextDescKeyTaskArchiveDryRunBlock    = "task-archive.dry-run-block"
	TextDescKeyTaskArchiveNoCompleted    = "task-archive.no-completed"
	TextDescKeyTaskArchivePendingRemain  = "task-archive.pending-remain"
	TextDescKeyTaskArchiveSkipIncomplete = "task-archive.skip-incomplete"
	TextDescKeyTaskArchiveSkipping       = "task-archive.skipping"
	TextDescKeyTaskArchiveSuccess        = "task-archive.success"
	TextDescKeyTaskArchiveSuccessWithAge = "task-archive.success-with-age"

	TextDescKeyTaskSnapshotHeaderFormat  = "task-snapshot.header-format"
	TextDescKeyTaskSnapshotCreatedFormat = "task-snapshot.created-format"
	TextDescKeyTaskSnapshotSaved         = "task-snapshot.saved"

	TextDescKeyWatchCloseLogError = "watch.close-log-error"
	TextDescKeyWatchDryRun        = "watch.dry-run"
	TextDescKeyWatchStopHint      = "watch.stop-hint"

	TextDescKeyWhyAdmonitionFormat = "why.admonition-format"
	TextDescKeyWhyBanner           = "why.banner"
	TextDescKeyWhyBlockquotePrefix = "why.blockquote-prefix"
	TextDescKeyWhyBoldFormat       = "why.bold-format"
	TextDescKeyWhyMenuItemFormat   = "why.menu-item-format"
	TextDescKeyWhyMenuPrompt       = "why.menu-prompt"

	TextDescKeyWatchApplyFailed   = "watch.apply-failed"
	TextDescKeyWatchApplySuccess  = "watch.apply-success"
	TextDescKeyWatchDryRunPreview = "watch.dry-run-preview"
	TextDescKeyWatchWatching      = "watch.watching"

	TextDescKeyDriftCleared = "drift.cleared"

	TextDescKeyMemoryDiffOldFormat = "memory.diff-old-format"
	TextDescKeyMemoryDiffNewFormat = "memory.diff-new-format"
	TextDescKeyMemoryImportSource  = "memory.import-source"

	TextDescKeyMemoryPublishTitle = "memory.publish-title"
	TextDescKeyMemoryPublishTasks = "memory.publish-tasks"
	TextDescKeyMemoryPublishDec   = "memory.publish-decisions"
	TextDescKeyMemoryPublishConv  = "memory.publish-conventions"
	TextDescKeyMemoryPublishLrn   = "memory.publish-learnings"

	TextDescKeyMemorySelectContent = "memory.select-content"
	TextDescKeyMemoryWriteMemory   = "memory.write-memory"
	TextDescKeyMemoryImportReview  = "memory.import-review"

	TextDescKeyMCPResConstitution = "mcp.res-constitution"
	TextDescKeyMCPResTasks        = "mcp.res-tasks"
	TextDescKeyMCPResConventions  = "mcp.res-conventions"
	TextDescKeyMCPResArchitecture = "mcp.res-architecture"
	TextDescKeyMCPResDecisions    = "mcp.res-decisions"
	TextDescKeyMCPResLearnings    = "mcp.res-learnings"
	TextDescKeyMCPResGlossary     = "mcp.res-glossary"
	TextDescKeyMCPResPlaybook     = "mcp.res-playbook"
	TextDescKeyMCPResAgent        = "mcp.res-agent"

	TextDescKeyMCPFailedMarshal = "mcp.failed-marshal"

	TextDescKeyMCPLoadContext = "mcp.load-context"

	TextDescKeyMCPMethodNotFound  = "mcp.method-not-found"
	TextDescKeyMCPPacketHeader    = "mcp.packet-header"
	TextDescKeyMCPParseError      = "mcp.parse-error"
	TextDescKeyMCPFileNotFound    = "mcp.file-not-found"
	TextDescKeyMCPInvalidParams   = "mcp.invalid-params"
	TextDescKeyMCPUnknownResource = "mcp.unknown-resource"
	TextDescKeyMCPUnknownTool     = "mcp.unknown-tool"

	TextDescKeyMCPToolStatusDesc      = "mcp.tool-status-desc"
	TextDescKeyMCPToolAddDesc         = "mcp.tool-add-desc"
	TextDescKeyMCPToolCompleteDesc    = "mcp.tool-complete-desc"
	TextDescKeyMCPToolDriftDesc       = "mcp.tool-drift-desc"
	TextDescKeyMCPToolRecallDesc      = "mcp.tool-recall-desc"
	TextDescKeyMCPToolWatchUpdateDesc = "mcp.tool-watch-update-desc"
	TextDescKeyMCPToolCompactDesc     = "mcp.tool-compact-desc"
	TextDescKeyMCPToolNextDesc        = "mcp.tool-next-desc"
	TextDescKeyMCPToolCheckTaskDesc   = "mcp.tool-check-task-desc"
	TextDescKeyMCPToolSessionDesc     = "mcp.tool-session-desc"
	TextDescKeyMCPToolRemindDesc      = "mcp.tool-remind-desc"
	TextDescKeyMCPToolPropType        = "mcp.tool-prop-type"
	TextDescKeyMCPToolPropContent     = "mcp.tool-prop-content"
	TextDescKeyMCPToolPropPriority    = "mcp.tool-prop-priority"
	TextDescKeyMCPToolPropContext     = "mcp.tool-prop-context"
	TextDescKeyMCPToolPropRationale   = "mcp.tool-prop-rationale"
	TextDescKeyMCPToolPropConseq      = "mcp.tool-prop-consequence"
	TextDescKeyMCPToolPropLesson      = "mcp.tool-prop-lesson"
	TextDescKeyMCPToolPropApplication = "mcp.tool-prop-application"
	TextDescKeyMCPToolPropQuery       = "mcp.tool-prop-query"
	TextDescKeyMCPToolPropLimit       = "mcp.tool-prop-limit"
	TextDescKeyMCPToolPropSince       = "mcp.tool-prop-since"
	TextDescKeyMCPToolPropEntryType   = "mcp.tool-prop-entry-type"
	TextDescKeyMCPToolPropMainContent = "mcp.tool-prop-main-content"
	TextDescKeyMCPToolPropCtxBg       = "mcp.tool-prop-ctx-background"
	TextDescKeyMCPToolPropArchive     = "mcp.tool-prop-archive"
	TextDescKeyMCPToolPropRecentAct   = "mcp.tool-prop-recent-action"
	TextDescKeyMCPToolPropEventType   = "mcp.tool-prop-event-type"
	TextDescKeyMCPToolPropCaller      = "mcp.tool-prop-caller"

	TextDescKeyMCPTypeContentRequired = "mcp.type-content-required"

	TextDescKeyMCPQueryRequired = "mcp.query-required"

	TextDescKeyMCPWriteFailed = "mcp.write-failed"

	TextDescKeyMCPAddedFormat         = "mcp.added-format"
	TextDescKeyMCPCompletedFormat     = "mcp.completed-format"
	TextDescKeyMCPStatusContextFormat = "mcp.status-context-format"
	TextDescKeyMCPStatusFilesFormat   = "mcp.status-files-format"
	TextDescKeyMCPStatusTokensFormat  = "mcp.status-tokens-format"
	TextDescKeyMCPStatusFileFormat    = "mcp.status-file-format"

	TextDescKeyMCPStatusOK    = "mcp.status-ok"
	TextDescKeyMCPStatusEmpty = "mcp.status-empty"

	TextDescKeyMCPDriftStatusFormat = "mcp.drift-status-format"
	TextDescKeyMCPDriftViolations   = "mcp.drift-violations"
	TextDescKeyMCPDriftWarnings     = "mcp.drift-warnings"
	TextDescKeyMCPDriftPassed       = "mcp.drift-passed"
	TextDescKeyMCPDriftIssueFormat  = "mcp.drift-issue-format"
	TextDescKeyMCPDriftPassedFormat = "mcp.drift-passed-format"

	TextDescKeyMCPSectionFormat = "mcp.section-format"

	TextDescKeyMCPAlsoNoted     = "mcp.also-noted"
	TextDescKeyMCPOmittedFormat = "mcp.omitted-format"

	TextDescKeyMCPBoundaryViolation   = "mcp.boundary-violation"
	TextDescKeyMCPInvalidSinceDate    = "mcp.invalid-since-date"
	TextDescKeyMCPFindSessionsFailed  = "mcp.find-sessions-failed"
	TextDescKeyMCPNoSessions          = "mcp.no-sessions"
	TextDescKeyMCPSessionsFoundFormat = "mcp.sessions-found-format"

	TextDescKeyMCPWatchCompletedFormat = "mcp.watch-completed-format"

	TextDescKeyMCPReviewStatus = "mcp.review-status"

	TextDescKeyMCPWroteFormat = "mcp.wrote-format"

	TextDescKeyMCPCompactClean    = "mcp.compact-clean"
	TextDescKeyMCPCompactedFormat = "mcp.compacted-format"

	TextDescKeyMCPNoTasks          = "mcp.no-tasks"
	TextDescKeyMCPNextTaskFormat   = "mcp.next-task-format"
	TextDescKeyMCPAllTasksComplete = "mcp.all-tasks-complete"
	TextDescKeyMCPCheckTaskFormat  = "mcp.check-task-format"
	TextDescKeyMCPCheckTaskHint    = "mcp.check-task-hint"

	TextDescKeyMCPEventTypeRequired = "mcp.event-type-required"

	TextDescKeyMCPSessionStartedCallerFormat = "mcp.session-started-caller-format"
	TextDescKeyMCPSessionStartedFormat       = "mcp.session-started-format"
	TextDescKeyMCPSessionEnding              = "mcp.session-ending"

	TextDescKeyMCPPendingUpdatesFormat = "mcp.pending-updates-format"
	TextDescKeyMCPReviewPending        = "mcp.review-pending"
	TextDescKeyMCPNoPending            = "mcp.no-pending"

	TextDescKeyMCPSessionStatsFormat = "mcp.session-stats-format"

	TextDescKeyMCPRecallItemFormat     = "mcp.recall-item-format"
	TextDescKeyMCPRecallProjectFormat  = "mcp.recall-project-format"
	TextDescKeyMCPRecallDurationFormat = "mcp.recall-duration-format"
	TextDescKeyMCPRecallFirstMsgFormat = "mcp.recall-first-msg-format"

	TextDescKeyMCPCompactMovedFormat    = "mcp.compact-moved-format"
	TextDescKeyMCPCompactArchiveWarning = "mcp.compact-archive-warning"
	TextDescKeyMCPCompactRemovedSectFmt = "mcp.compact-removed-sections-format"

	TextDescKeyMCPPendingItemFormat = "mcp.pending-item-format"

	TextDescKeyMCPReminderItemFormat   = "mcp.reminder-item-format"
	TextDescKeyMCPReminderNotDueFormat = "mcp.reminder-not-due-format"

	TextDescKeyMCPUnknownEventType = "mcp.unknown-event-type"

	TextDescKeyMCPReadRemindersFailed = "mcp.read-reminders-failed"
	TextDescKeyMCPNoReminders         = "mcp.no-reminders"
	TextDescKeyMCPRemindersFormat     = "mcp.reminders-format"

	TextDescKeyMCPUnknownPrompt = "mcp.unknown-prompt"

	TextDescKeyMCPURIRequired = "mcp.uri-required"

	TextDescKeyMCPPromptSessionStartDesc = "mcp.prompt-session-start-desc"
	TextDescKeyMCPPromptAddDecisionDesc  = "mcp.prompt-add-decision-desc"
	TextDescKeyMCPPromptAddLearningDesc  = "mcp.prompt-add-learning-desc"
	TextDescKeyMCPPromptReflectDesc      = "mcp.prompt-reflect-desc"
	TextDescKeyMCPPromptCheckpointDesc   = "mcp.prompt-checkpoint-desc"

	TextDescKeyMCPPromptArgDecisionTitle  = "mcp.prompt-arg-decision-title"
	TextDescKeyMCPPromptArgDecisionCtx    = "mcp.prompt-arg-decision-ctx"
	TextDescKeyMCPPromptArgDecisionRat    = "mcp.prompt-arg-decision-rationale"
	TextDescKeyMCPPromptArgDecisionConseq = "mcp.prompt-arg-decision-consequence"
	TextDescKeyMCPPromptArgLearningTitle  = "mcp.prompt-arg-learning-title"
	TextDescKeyMCPPromptArgLearningCtx    = "mcp.prompt-arg-learning-ctx"
	TextDescKeyMCPPromptArgLearningLesson = "mcp.prompt-arg-learning-lesson"
	TextDescKeyMCPPromptArgLearningApp    = "mcp.prompt-arg-learning-app"

	TextDescKeyMCPPromptSessionStartHeader  = "mcp.prompt-session-start-header"
	TextDescKeyMCPPromptSessionStartFooter  = "mcp.prompt-session-start-footer"
	TextDescKeyMCPPromptSessionStartResultD = "mcp.prompt-session-start-result-desc"
	TextDescKeyMCPPromptSectionFormat       = "mcp.prompt-section-format"

	TextDescKeyMCPPromptAddDecisionHeader   = "mcp.prompt-add-decision-header"
	TextDescKeyMCPPromptAddDecisionFieldFmt = "mcp.prompt-add-decision-field-format"

	TextDescKeyMCPPromptLabelDecision    = "mcp.prompt-label-decision"
	TextDescKeyMCPPromptLabelContext     = "mcp.prompt-label-context"
	TextDescKeyMCPPromptLabelRationale   = "mcp.prompt-label-rationale"
	TextDescKeyMCPPromptLabelConsequence = "mcp.prompt-label-consequence"
	TextDescKeyMCPPromptLabelLearning    = "mcp.prompt-label-learning"
	TextDescKeyMCPPromptLabelLesson      = "mcp.prompt-label-lesson"
	TextDescKeyMCPPromptLabelApplication = "mcp.prompt-label-application"

	TextDescKeyMCPPromptAddDecisionFooter  = "mcp.prompt-add-decision-footer"
	TextDescKeyMCPPromptAddDecisionResultD = "mcp.prompt-add-decision-result-desc"

	TextDescKeyMCPPromptAddLearningHeader   = "mcp.prompt-add-learning-header"
	TextDescKeyMCPPromptAddLearningFieldFmt = "mcp.prompt-add-learning-field-format"
	TextDescKeyMCPPromptAddLearningFooter   = "mcp.prompt-add-learning-footer"
	TextDescKeyMCPPromptAddLearningResultD  = "mcp.prompt-add-learning-result-desc"

	TextDescKeyMCPPromptReflectBody    = "mcp.prompt-reflect-body"
	TextDescKeyMCPPromptReflectResultD = "mcp.prompt-reflect-result-desc"

	TextDescKeyMCPPromptCheckpointHeader      = "mcp.prompt-checkpoint-header"
	TextDescKeyMCPPromptCheckpointStatsFormat = "mcp.prompt-checkpoint-stats-format"
	TextDescKeyMCPPromptCheckpointSteps       = "mcp.prompt-checkpoint-steps"
	TextDescKeyMCPPromptCheckpointResultD     = "mcp.prompt-checkpoint-result-desc"

	TextDescKeyDriftDeadPath       = "drift.dead-path"
	TextDescKeyDriftEntryCount     = "drift.entry-count"
	TextDescKeyDriftMissingFile    = "drift.missing-file"
	TextDescKeyDriftRegenerated    = "drift.regenerated"
	TextDescKeyDriftMissingPackage = "drift.missing-package"
	TextDescKeyDriftSecret         = "drift.secret"
	TextDescKeyDriftStaleAge       = "drift.stale-age"
	TextDescKeyDriftStaleness      = "drift.staleness"

	TextDescKeyJournalMocSessionLink    = "journal.moc.session-link"
	TextDescKeyJournalMocNavDescription = "journal.moc.nav-description"
	TextDescKeyJournalMocBrowseBy       = "journal.moc.browse-by"
	TextDescKeyJournalMocTopicsDesc     = "journal.moc.topics-description"
	TextDescKeyJournalMocFilesDesc      = "journal.moc.files-description"
	TextDescKeyJournalMocTypesDesc      = "journal.moc.types-description"

	TextDescKeyWriteAddedTo  = "write.added-to"
	TextDescKeyWriteArchived = "write.archived"

	TextDescKeyWriteBackupResult  = "write.backup-result"
	TextDescKeyWriteBackupSMBDest = "write.backup-smb-dest"

	TextDescKeyWriteBootstrapDir       = "write.bootstrap-dir"
	TextDescKeyWriteBootstrapFiles     = "write.bootstrap-files"
	TextDescKeyWriteBootstrapNextSteps = "write.bootstrap-next-steps"
	TextDescKeyWriteBootstrapNumbered  = "write.bootstrap-numbered"
	TextDescKeyWriteBootstrapRules     = "write.bootstrap-rules"
	TextDescKeyWriteBootstrapSep       = "write.bootstrap-sep"
	TextDescKeyWriteBootstrapTitle     = "write.bootstrap-title"
	TextDescKeyWriteBootstrapWarning   = "write.bootstrap-warning"

	TextDescKeyWriteCompletedTask = "write.completed-task"

	TextDescKeyWriteConfigProfileBase = "write.config-profile-base"
	TextDescKeyWriteConfigProfileDev  = "write.config-profile-dev"
	TextDescKeyWriteConfigProfileNone = "write.config-profile-none"

	TextDescKeyWriteDepsLookingFor = "write.deps-looking-for"
	TextDescKeyWriteDepsNoDeps     = "write.deps-no-deps"
	TextDescKeyWriteDepsNoProject  = "write.deps-no-project"
	TextDescKeyWriteDepsUseType    = "write.deps-use-type"

	TextDescKeyWriteDryRun                     = "write.dry-run"
	TextDescKeyWriteExistsWritingAsAlternative = "write.exists-writing-as-alternative"

	TextDescKeyWriteHookCopilotCreated     = "write.hook-copilot-created"
	TextDescKeyWriteHookCopilotForceHint   = "write.hook-copilot-force-hint"
	TextDescKeyWriteHookCopilotMerged      = "write.hook-copilot-merged"
	TextDescKeyWriteHookCopilotSessionsDir = "write.hook-copilot-sessions-dir"
	TextDescKeyWriteHookCopilotSkipped     = "write.hook-copilot-skipped"
	TextDescKeyWriteHookCopilotSummary     = "write.hook-copilot-summary"
	TextDescKeyWriteHookUnknownTool        = "write.hook-unknown-tool"

	TextDescKeyWriteImportAdded          = "write.import-added"
	TextDescKeyWriteImportClassified     = "write.import-classified"
	TextDescKeyWriteImportClassifiedSkip = "write.import-classified-skip"
	TextDescKeyWriteImportDuplicates     = "write.import-duplicates"
	TextDescKeyWriteImportEntry          = "write.import-entry"
	TextDescKeyWriteImportFound          = "write.import-found"
	TextDescKeyWriteImportNoEntries      = "write.import-no-entries"
	TextDescKeyWriteImportScanning       = "write.import-scanning"
	TextDescKeyWriteImportSkipped        = "write.import-skipped"
	TextDescKeyWriteImportSummary        = "write.import-summary"
	TextDescKeyWriteImportSummaryDryRun  = "write.import-summary-dry-run"

	TextDescKeyWriteInitAborted           = "write.init-aborted"
	TextDescKeyWriteInitBackup            = "write.init-backup"
	TextDescKeyWriteInitCreatedDir        = "write.init-created-dir"
	TextDescKeyWriteInitCreatedWith       = "write.init-created-with"
	TextDescKeyWriteInitCreatingRootFiles = "write.init-creating-root-files"
	TextDescKeyWriteInitCtxContentExists  = "write.init-ctx-content-exists"
	TextDescKeyWriteInitExistsSkipped     = "write.init-exists-skipped"

	TextDescKeyWriteInitFileCreated     = "write.init-file-created"
	TextDescKeyWriteInitFileExistsNoCtx = "write.init-file-exists-no-ctx"

	TextDescKeyWriteInitGitignoreReview  = "write.init-gitignore-review"
	TextDescKeyWriteInitGitignoreUpdated = "write.init-gitignore-updated"

	TextDescKeyWriteInitMakefileAppended = "write.init-makefile-appended"
	TextDescKeyWriteInitMakefileCreated  = "write.init-makefile-created"
	TextDescKeyWriteInitMakefileIncludes = "write.init-makefile-includes"

	TextDescKeyWriteInitMerged          = "write.init-merged"
	TextDescKeyWriteInitNextStepsBlock  = "write.init-next-steps-block"
	TextDescKeyWriteInitNoChanges       = "write.init-no-changes"
	TextDescKeyWriteInitOverwritePrompt = "write.init-overwrite-prompt"

	TextDescKeyWriteInitPermsAllow         = "write.init-perms-allow"
	TextDescKeyWriteInitPermsAllowDeny     = "write.init-perms-allow-deny"
	TextDescKeyWriteInitPermsDeduped       = "write.init-perms-deduped"
	TextDescKeyWriteInitPermsDeny          = "write.init-perms-deny"
	TextDescKeyWriteInitPermsMergedDeduped = "write.init-perms-merged-deduped"

	TextDescKeyWriteInitPluginAlreadyEnabled = "write.init-plugin-already-enabled"
	TextDescKeyWriteInitPluginEnabled        = "write.init-plugin-enabled"
	TextDescKeyWriteInitPluginSkipped        = "write.init-plugin-skipped"

	TextDescKeyWriteInitScratchpadKeyCreated = "write.init-scratchpad-key-created"
	TextDescKeyWriteInitScratchpadNoKey      = "write.init-scratchpad-no-key"
	TextDescKeyWriteInitScratchpadPlaintext  = "write.init-scratchpad-plaintext"

	TextDescKeyWriteInitSettingUpPermissions = "write.init-setting-up-permissions"

	TextDescKeyWriteInitSkippedDir   = "write.init-skipped-dir"
	TextDescKeyWriteInitSkippedPlain = "write.init-skipped-plain"

	TextDescKeyWriteInitUpdatedCtxSection    = "write.init-updated-ctx-section"
	TextDescKeyWriteInitUpdatedPlanSection   = "write.init-updated-plan-section"
	TextDescKeyWriteInitUpdatedPromptSection = "write.init-updated-prompt-section"

	TextDescKeyWriteInitWarnNonFatal = "write.init-warn-non-fatal"
	TextDescKeyWriteInitialized      = "write.initialized"

	TextDescKeyWriteJournalOrphanRemoved      = "write.journal-orphan-removed"
	TextDescKeyWriteJournalSiteBuilding       = "write.journal-site-building"
	TextDescKeyWriteJournalSiteGeneratedBlock = "write.journal-site-generated-block"
	TextDescKeyWriteJournalSiteStarting       = "write.journal-site-starting"
	TextDescKeyWriteJournalSyncLocked         = "write.journal-sync-locked"
	TextDescKeyWriteJournalSyncLockedCount    = "write.journal-sync-locked-count"
	TextDescKeyWriteJournalSyncMatch          = "write.journal-sync-match"
	TextDescKeyWriteJournalSyncNone           = "write.journal-sync-none"
	TextDescKeyWriteJournalSyncUnlocked       = "write.journal-sync-unlocked"
	TextDescKeyWriteJournalSyncUnlockedCount  = "write.journal-sync-unlocked-count"

	TextDescKeyWriteLines         = "write.lines"
	TextDescKeyWriteLinesPrevious = "write.lines-previous"

	TextDescKeyWriteLockUnlockEntry     = "write.lock-unlock-entry"
	TextDescKeyWriteLockUnlockNoChanges = "write.lock-unlock-no-changes"
	TextDescKeyWriteLockUnlockSummary   = "write.lock-unlock-summary"
	TextDescKeyWriteLoopGeneratedBlock  = "write.loop-generated-block"

	TextDescKeyWriteLoopMaxIterations = "write.loop-max-iterations"
	TextDescKeyWriteLoopUnlimited     = "write.loop-unlimited"

	TextDescKeyWriteMemoryArchives         = "write.memory-archives"
	TextDescKeyWriteMemoryBridgeHeader     = "write.memory-bridge-header"
	TextDescKeyWriteMemoryDriftDetected    = "write.memory-drift-detected"
	TextDescKeyWriteMemoryDriftNone        = "write.memory-drift-none"
	TextDescKeyWriteMemoryLastSync         = "write.memory-last-sync"
	TextDescKeyWriteMemoryLastSyncNever    = "write.memory-last-sync-never"
	TextDescKeyWriteMemoryMirror           = "write.memory-mirror"
	TextDescKeyWriteMemoryMirrorLines      = "write.memory-mirror-lines"
	TextDescKeyWriteMemoryMirrorNotSynced  = "write.memory-mirror-not-synced"
	TextDescKeyWriteMemoryNoChanges        = "write.memory-no-changes"
	TextDescKeyWriteMemorySource           = "write.memory-source"
	TextDescKeyWriteMemorySourceLines      = "write.memory-source-lines"
	TextDescKeyWriteMemorySourceLinesDrift = "write.memory-source-lines-drift"
	TextDescKeyWriteMemorySourceNotActive  = "write.memory-source-not-active"

	TextDescKeyWriteMirror = "write.mirror"

	TextDescKeyWriteMovingTask = "write.moving-task"

	TextDescKeyWriteNewContent = "write.new-content"

	TextDescKeyWriteObsidianGenerated        = "write.obsidian-generated"
	TextDescKeyWriteObsidianNextStepsHeading = "write.obsidian-next-steps-heading"
	TextDescKeyWriteObsidianNextSteps        = "write.obsidian-next-steps"

	TextDescKeyWritePadBlobWritten = "write.pad-blob-written"

	TextDescKeyWritePadEmpty = "write.pad-empty"

	TextDescKeyWritePadEntryAdded   = "write.pad-entry-added"
	TextDescKeyWritePadEntryMoved   = "write.pad-entry-moved"
	TextDescKeyWritePadEntryRemoved = "write.pad-entry-removed"
	TextDescKeyWritePadEntryUpdated = "write.pad-entry-updated"

	TextDescKeyWritePadExportDone        = "write.pad-export-done"
	TextDescKeyWritePadExportNone        = "write.pad-export-none"
	TextDescKeyWritePadExportPlan        = "write.pad-export-plan"
	TextDescKeyWritePadExportSummary     = "write.pad-export-summary"
	TextDescKeyWritePadExportVerbDone    = "write.pad-export-verb-done"
	TextDescKeyWritePadExportVerbDryRun  = "write.pad-export-verb-dry-run"
	TextDescKeyWritePadExportWriteFailed = "write.pad-export-write-failed"

	TextDescKeyWritePadImportBlobAdded    = "write.pad-import-blob-added"
	TextDescKeyWritePadImportBlobNone     = "write.pad-import-blob-none"
	TextDescKeyWritePadImportBlobSkipped  = "write.pad-import-blob-skipped"
	TextDescKeyWritePadImportBlobSummary  = "write.pad-import-blob-summary"
	TextDescKeyWritePadImportBlobTooLarge = "write.pad-import-blob-too-large"
	TextDescKeyWritePadImportCloseWarning = "write.pad-import-close-warning"
	TextDescKeyWritePadImportDone         = "write.pad-import-done"
	TextDescKeyWritePadImportNone         = "write.pad-import-none"

	TextDescKeyWritePadKeyCreated = "write.pad-key-created"

	TextDescKeyWritePadMergeAdded         = "write.pad-merge-added"
	TextDescKeyWritePadMergeBinaryWarning = "write.pad-merge-binary-warning"
	TextDescKeyWritePadMergeBlobConflict  = "write.pad-merge-blob-conflict"
	TextDescKeyWritePadMergeDone          = "write.pad-merge-done"
	TextDescKeyWritePadMergeDryRun        = "write.pad-merge-dry-run"
	TextDescKeyWritePadMergeDupe          = "write.pad-merge-dupe"
	TextDescKeyWritePadMergeNone          = "write.pad-merge-none"
	TextDescKeyWritePadMergeNoneNew       = "write.pad-merge-none-new"

	TextDescKeyWritePadResolveEntry  = "write.pad-resolve-entry"
	TextDescKeyWritePadResolveHeader = "write.pad-resolve-header"

	TextDescKeyWritePathExists = "write.path-exists"

	TextDescKeyWritePaused = "write.paused"

	TextDescKeyWritePrefixError = "write.prefix-error"

	TextDescKeyWritePromptCreated = "write.prompt-created"
	TextDescKeyWritePromptItem    = "write.prompt-item"
	TextDescKeyWritePromptNone    = "write.prompt-none"
	TextDescKeyWritePromptRemoved = "write.prompt-removed"

	TextDescKeyWritePublishBlock       = "write.publish-block"
	TextDescKeyWritePublishBudget      = "write.publish-budget"
	TextDescKeyWritePublishConventions = "write.publish-conventions"
	TextDescKeyWritePublishDecisions   = "write.publish-decisions"
	TextDescKeyWritePublishDone        = "write.publish-done"
	TextDescKeyWritePublishDryRun      = "write.publish-dry-run"
	TextDescKeyWritePublishHeader      = "write.publish-header"
	TextDescKeyWritePublishLearnings   = "write.publish-learnings"
	TextDescKeyWritePublishSourceFiles = "write.publish-source-files"
	TextDescKeyWritePublishTasks       = "write.publish-tasks"
	TextDescKeyWritePublishTotal       = "write.publish-total"

	TextDescKeyWriteReminderAdded        = "write.reminder-added"
	TextDescKeyWriteReminderAfterSuffix  = "write.reminder-after-suffix"
	TextDescKeyWriteReminderDismissed    = "write.reminder-dismissed"
	TextDescKeyWriteReminderDismissedAll = "write.reminder-dismissed-all"
	TextDescKeyWriteReminderItem         = "write.reminder-item"
	TextDescKeyWriteReminderNone         = "write.reminder-none"
	TextDescKeyWriteReminderNotDue       = "write.reminder-not-due"

	TextDescKeyWriteRestoreAdded              = "write.restore-added"
	TextDescKeyWriteRestoreDenyDroppedHeader  = "write.restore-deny-dropped-header"
	TextDescKeyWriteRestoreDenyRestoredHeader = "write.restore-deny-restored-header"
	TextDescKeyWriteRestoreDone               = "write.restore-done"
	TextDescKeyWriteRestoreDroppedHeader      = "write.restore-dropped-header"
	TextDescKeyWriteRestoreMatch              = "write.restore-match"
	TextDescKeyWriteRestoreNoLocal            = "write.restore-no-local"
	TextDescKeyWriteRestorePermMatch          = "write.restore-perm-match"
	TextDescKeyWriteRestoreRemoved            = "write.restore-removed"
	TextDescKeyWriteRestoreRestoredHeader     = "write.restore-restored-header"

	TextDescKeyWriteResumed = "write.resumed"

	TextDescKeyWriteSetupDone   = "write.setup-done"
	TextDescKeyWriteSetupPrompt = "write.setup-prompt"

	TextDescKeyWriteSkillLine    = "write.skill-line"
	TextDescKeyWriteSkillsHeader = "write.skills-header"

	TextDescKeyWriteSnapshotSaved   = "write.snapshot-saved"
	TextDescKeyWriteSnapshotUpdated = "write.snapshot-updated"

	TextDescKeyWriteSource = "write.source"

	TextDescKeyWriteStatusActivityHeader = "write.status-activity-header"
	TextDescKeyWriteStatusActivityItem   = "write.status-activity-item"
	TextDescKeyWriteStatusDrift          = "write.status-drift"
	TextDescKeyWriteStatusFileCompact    = "write.status-file-compact"
	TextDescKeyWriteStatusFileVerbose    = "write.status-file-verbose"
	TextDescKeyWriteStatusHeaderBlock    = "write.status-header-block"
	TextDescKeyWriteStatusNoDrift        = "write.status-no-drift"
	TextDescKeyWriteStatusPreviewLine    = "write.status-preview-line"

	TextDescKeyWriteSynced            = "write.synced"
	TextDescKeyWriteSyncAction        = "write.sync-action"
	TextDescKeyWriteSyncDryRun        = "write.sync-dry-run"
	TextDescKeyWriteSyncDryRunSummary = "write.sync-dry-run-summary"
	TextDescKeyWriteSyncHeader        = "write.sync-header"
	TextDescKeyWriteSyncInSync        = "write.sync-in-sync"
	TextDescKeyWriteSyncSeparator     = "write.sync-separator"
	TextDescKeyWriteSyncSuggestion    = "write.sync-suggestion"
	TextDescKeyWriteSyncSummary       = "write.sync-summary"

	TextDescKeyWriteTestFiltered  = "write.test-filtered"
	TextDescKeyWriteTestNoWebhook = "write.test-no-webhook"
	TextDescKeyWriteTestResult    = "write.test-result"
	TextDescKeyWriteTestWorking   = "write.test-working"

	TextDescKeyWriteTimeDayAgo     = "write.time-day-ago"
	TextDescKeyWriteTimeDaysAgo    = "write.time-days-ago"
	TextDescKeyWriteTimeHourAgo    = "write.time-hour-ago"
	TextDescKeyWriteTimeHoursAgo   = "write.time-hours-ago"
	TextDescKeyWriteTimeJustNow    = "write.time-just-now"
	TextDescKeyWriteTimeMinuteAgo  = "write.time-minute-ago"
	TextDescKeyWriteTimeMinutesAgo = "write.time-minutes-ago"

	TextDescKeyWriteUnpublishDone     = "write.unpublish-done"
	TextDescKeyWriteUnpublishNotFound = "write.unpublish-not-found"

	TextDescKeyStopwords = "stopwords"

	// Headings, column headers, and navigation labels (headings.yaml).
	TextDescKeyHeadingDecisions     = "heading.decisions"
	TextDescKeyHeadingLearnings     = "heading.learnings"
	TextDescKeyHeadingLearningStart = "heading.learning-entry-start"

	TextDescKeyColumnDecision = "column.decision"
	TextDescKeyColumnLearning = "column.learning"

	TextDescKeyLabelBoldReminder = "label.bold-reminder"

	TextDescKeyLabelToolOutput = "label.tool-output"

	TextDescKeyLabelSuggestionMode = "label.suggestion-mode"
)
