//   /    Context:                     https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package config

// Markdown format templates for context entries.
//
// These templates define the structure of entries written to .context/ files
// by the add command. Each uses fmt.Sprintf verbs for interpolation.
const (
	// TplTask formats a task checkbox line.
	// Args: content, priorityTag, timestamp.
	TplTask = "- [ ] %s%s #added:%s\n"

	// TplTaskPriority formats the inline priority tag.
	// Args: priority level.
	TplTaskPriority = " #priority:%s"

	// TplLearning formats a learning section with all ADR-style fields.
	// Args: timestamp, title, context, lesson, application.
	TplLearning = `## [%s] %s

**Context**: %s

**Lesson**: %s

**Application**: %s
`

	// TplConvention formats a convention list item.
	// Args: content.
	TplConvention = "- %s\n"

	// TplDecision formats a decision section with all ADR fields.
	// Args: timestamp, title, context, title (repeated), rationale, consequences.
	TplDecision = `## [%s] %s

**Status**: Accepted

**Context**: %s

**Decision**: %s

**Rationale**: %s

**Consequences**: %s
`
)

// Journal site format templates.
//
// These templates define the structure of generated journal site pages.
// Each uses fmt.Sprintf verbs for interpolation.
const (
	// TplJournalSiteReadme formats the README for the journal-site directory.
	// Args: journalDir.
	TplJournalSiteReadme = `# journal-site (generated)

This directory is generated by ` + "`ctx journal site`" + ` and is read-only.
Do not edit files here — changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal site          # generate
ctx journal site --serve  # generate and preview
` + "```" + `
`

	// TplJournalIndexIntro is the introductory line on the journal index.
	TplJournalIndexIntro = "Browse your AI session history."

	// TplJournalIndexStats formats the session/suggestion count line.
	// Args: regular count, suggestion count.
	TplJournalIndexStats = "**Sessions**: %d | **Suggestions**: %d"

	// TplJournalSuggestionsNote is the description under the suggestions heading.
	TplJournalSuggestionsNote = "*Auto-generated suggestion prompts from Claude Code.*"

	// TplJournalMonthHeading formats a month section heading.
	// Args: month string (YYYY-MM).
	TplJournalMonthHeading = "## %s"

	// TplJournalIndexEntry formats a single entry in the journal index.
	// Args: timeStr, title, link, project, size.
	TplJournalIndexEntry = "- %s[%s](%s.md)%s `%s`"

	// TplJournalSourceLink formats the "View source" link injected into entries.
	// Args: absPath, relPath, relPath.
	TplJournalSourceLink = `*[View source](file://%s) · <code>%s</code>*` +
		` <button onclick="navigator.clipboard.writeText('%s')" title="Copy path"` +
		` style="cursor:pointer;border:none;background:none;font-size:0.8em;vertical-align:middle">` +
		`&#x2398;</button>`

	// TplJournalTopicStats formats the topics index summary line.
	// Args: topic count, session count, popular count, longtail count.
	TplJournalTopicStats = "**%d topics** across **%d sessions**— **%d popular**, **%d long-tail**"

	// TplJournalTopicPageStats formats an individual topic page summary.
	// Args: session count.
	TplJournalTopicPageStats = "**%d sessions** with this topic."

	// TplJournalFileStats formats the key files index summary line.
	// Args: file count, session count, popular count, longtail count.
	TplJournalFileStats = "**%d files** across **%d sessions** — **%d popular**, **%d long-tail**"

	// TplJournalFilePageStats formats an individual key file page summary.
	// Args: session count.
	TplJournalFilePageStats = "**%d sessions** touching this file."

	// TplJournalTypeStats formats the session types index summary line.
	// Args: type count, session count.
	TplJournalTypeStats = "**%d types** across **%d sessions**"

	// TplJournalTypePageStats formats an individual type page summary.
	// Args: session count, type name.
	TplJournalTypePageStats = "**%d sessions** of type *%s*."

	// TplJournalPageHeading formats a Markdown heading for an index page.
	// Args: name.
	TplJournalPageHeading = "# %s"

	// TplJournalCodePageHeading formats a Markdown heading with code styling.
	// Args: path.
	TplJournalCodePageHeading = "# `%s`"

	// TplJournalSubpageEntry formats a session link on a subpage (topic, file, type).
	// Args: timeStr, title, linkPrefix, link.
	TplJournalSubpageEntry = "- %s[%s](%s%s.md)"

	// TplJournalLongtailEntry formats an inline longtail topic entry.
	// Args: name, title, link.
	TplJournalLongtailEntry = "- **%s** — [%s](../%s.md)"

	// TplJournalLongtailCodeEntry formats an inline longtail key file entry.
	// Args: path, title, link.
	TplJournalLongtailCodeEntry = "- `%s` — [%s](../%s.md)"

	// TplJournalNavItem formats a navigation item in zensical.toml.
	// Args: label, path.
	TplJournalNavItem = `  { "%s" = "%s" },`

	// TplJournalNavSection formats a navigation section opening.
	// Args: label.
	TplJournalNavSection = `  { "%s" = [`

	// TplJournalNavSessionItem formats a session entry in navigation.
	// Args: title, filename.
	TplJournalNavSessionItem = `    { "%s" = "%s" },`

	// TplZensicalProject is the [project] section of zensical.toml.
	TplZensicalProject = `[project]
site_name = "ctx: Session Journal"
site_description = "AI session history and notes"
site_author = "Jose Alekhinne <alekhinejose@gmail.com>"
site_url = "https://ctx.ist/"
repo_url = "https://github.com/ActiveMemory/ctx"
repo_name = "ActiveMemory/ctx"
copyright = """
Copyright &copy; 2026&ndash;present <a href="https://github.com/ActiveMemory/ctx/">Context contributors</a>.<br>
Context's code is distributed under
<a href="https://github.com/ActiveMemory/ctx/blob/main/LICENSE"><strong>Apache (v2.0)</strong></a>.<br>
"""

`

	// TplSessionInsightsSummary formats the insights extraction summary.
	// Args: decision count, learning count.
	TplSessionInsightsSummary = "*Found %d potential decisions and %d potential learnings*"

	// TplSessionFilename formats a session save filename.
	// Args: timestamp, topic.
	TplSessionFilename = "%s-%s.md"

	// TplSessionTotalMessages formats the total message count footer.
	// Args: count.
	TplSessionTotalMessages = "*Total messages: %d*"

	// TplSessionRoleHeading formats a role heading in session transcripts.
	// Args: role.
	TplSessionRoleHeading = "## %s"

	// TplSessionTimestamp formats an italic timestamp line.
	// Args: formatted time.
	TplSessionTimestamp = "*%s*"

	// TplSessionThinkingOpen is the collapsible thinking block opening.
	TplSessionThinkingOpen = "<details>\n<summary>\U0001f4ad Thinking</summary>"

	// TplSessionToolName formats a tool invocation heading.
	// Args: tool name.
	TplSessionToolName = "**\U0001f527 Tool: %s**"

	// TplSessionToolParam formats a tool parameter line.
	// Args: key, value.
	TplSessionToolParam = "- %s: `%s`"

	// TplSessionToolResult is the tool result heading.
	TplSessionToolResult = "**\U0001f4cb Tool Result**"

	// TplSessionTruncated is the truncation marker for long content.
	TplSessionTruncated = "...(truncated)"

	// TplSessionHeading formats the session snapshot title.
	// Args: topic.
	TplSessionHeading = "# Session: %s"

	// TplSessionPlaceholderSummary is the placeholder in the summary section.
	TplSessionPlaceholderSummary = "[Describe what was accomplished in this session]"

	// TplSessionPlaceholderNoDecisions is shown when no decisions are found.
	TplSessionPlaceholderNoDecisions = "[No recent decisions found]"

	// TplSessionPlaceholderNoLearnings is shown when no learnings are found.
	TplSessionPlaceholderNoLearnings = "[No recent learnings found]"

	// TplSessionPlaceholderNextTasks is the placeholder for next-session tasks.
	TplSessionPlaceholderNextTasks = "[List tasks to continue in the next session]"

	// TplRecallFilename formats a journal entry filename.
	// Args: date, slug, shortID.
	TplRecallFilename = "%s-%s-%s.md"

	// TplRecallTokens formats the token stats line.
	// Args: total, in, out.
	TplRecallTokens = "**Tokens**: %s (in: %s, out: %s)"

	// TplRecallPartOf formats the part indicator.
	// Args: part, totalParts.
	TplRecallPartOf = "**Part %d of %d**"

	// TplRecallConversationContinued formats the continued conversation heading.
	// Args: previous part number.
	TplRecallConversationContinued = "## Conversation (continued from part %d)"

	// TplRecallTurnHeader formats a conversation turn heading.
	// Args: msgNum, role, time.
	TplRecallTurnHeader = "### %d. %s (%s)"

	// TplRecallToolUse formats a tool use line.
	// Args: formatted tool name and args.
	TplRecallToolUse = "🔧 **%s**"

	// TplRecallToolCount formats a tool usage count line.
	// Args: name, count.
	TplRecallToolCount = "- %s: %d"

	// TplRecallSummaryPlaceholder is the placeholder text in the summary section.
	TplRecallSummaryPlaceholder = "[Add your summary of this session]"

	// TplRecallErrorMarker is the error indicator for tool results.
	TplRecallErrorMarker = "❌ Error"

	// TplRecallDetailsSummary formats the summary text for collapsible content.
	// Args: line count.
	TplRecallDetailsSummary = "%d lines"

	// TplRecallDetailsOpen formats the opening HTML for collapsible content.
	// Args: summary text.
	TplRecallDetailsOpen = "<details>\n<summary>%s</summary>"

	// TplRecallDetailsClose is the closing HTML for collapsible content.
	TplRecallDetailsClose = "</details>"

	// TplRecallFencedBlock formats content inside code fences.
	// Args: fence, content, fence.
	TplRecallFencedBlock = "%s\n%s\n%s"

	// TplRecallNavPrev formats the previous part navigation link.
	// Args: filename.
	TplRecallNavPrev = "[← Previous](%s)"

	// TplRecallNavNext formats the next part navigation link.
	// Args: filename.
	TplRecallNavNext = "[Next →](%s)"

	// TplRecallPartFilename formats a multi-part filename.
	// Args: baseName, part.
	TplRecallPartFilename = "%s-p%d.md"

	// TplLoadBudget formats the token budget summary line.
	// Args: budget, totalTokens.
	TplLoadBudget = "Token Budget: %d | Available: %d"

	// TplLoadTruncated formats the truncation notice for budget-limited output.
	// Args: fileName.
	TplLoadTruncated = "*[Truncated: %s and remaining files excluded due to token budget]*"

	// TplLoadSectionHeading formats a file section heading in assembled output.
	// Args: title.
	TplLoadSectionHeading = "## %s"

	// TplLoopScript is the bash script template for the Ralph Loop.
	// Args: promptFile, completionMsg, maxIterCheck, aiCommand, loopComplete.
	TplLoopScript = `#!/bin/bash
#
# Context: Ralph Loop Script
# Generated by: ctx loop
#
# This script runs an AI assistant in a loop until completion.
# The AI works on the same prompt file repeatedly, building on
# previous work visible in files and git history.
#

set -e

PROMPT_FILE="%s"
COMPLETION_SIGNAL="%s"
ITERATION=0

echo "Starting Ralph Loop"
echo "==================="
echo "Prompt: $PROMPT_FILE"
echo "Completion signal: $COMPLETION_SIGNAL"
echo ""

# Ensure prompt file exists
if [ ! -f "$PROMPT_FILE" ]; then
    echo "Error: Prompt file not found: $PROMPT_FILE"
    exit 1
fi

while true; do
    ITERATION=$((ITERATION + 1))
    echo ""
    echo "=== Iteration $ITERATION ==="
    echo ""
%s
    # Run the AI tool
    OUTPUT=$(%s 2>&1) || true

    echo "$OUTPUT"

    # Check for completion signal
    if echo "$OUTPUT" | grep -q "$COMPLETION_SIGNAL"; then
        echo ""
        echo "%s"
        echo "Detected completion signal: $COMPLETION_SIGNAL"
        echo "Total iterations: $ITERATION"
        break
    fi

    # Small delay to prevent runaway loops
    sleep 1
done
`

	// TplLoopMaxIter is the iteration-limit check block for the loop script.
	// Args: maxIterations, maxIterations.
	TplLoopMaxIter = `
    # Check iteration limit
    if [ $ITERATION -ge %d ]; then
        echo "Reached maximum iterations (%d)"
        break
    fi`

	// TplZensicalTheme is the theme and extras section of zensical.toml.
	TplZensicalTheme = `

[project.theme]
language = "en"
features = [
    "content.code.copy",
    "navigation.instant",
    "navigation.top",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ActiveMemory/ctx"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/kampus"

[project.extra]
generator = false
`
)
